analytics:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: ACCOUNTADMIN
      warehouse: TAXI_WH
      database: TAXI_DATA
      schema: DBT
      threads: 4
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: ACCOUNTADMIN
      warehouse: TAXI_WH
      database: TAXI_DATA
      schema: PROD
      threads: 4      
